/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testcases;

import org.testng.annotations.Test;

import common.WebDriverBase;

public class test1 extends WebDriverBase{
	
    @Test 
    public void testSomeLibraryMethod() throws InterruptedException{
    	WebDriverBase.getDriver().get("https://www.facebook.com");   
    	}
    
    @Test
    public void testSecondLibraryMethod() throws InterruptedException{
    	WebDriverBase.getDriver().get("https://www.salesforce.com");   
    	}
}
